dspace-group/simphera-reference-architecture-azure

.gitignore
README.md
common/.gitignore
common/config_template.tfvars
common/main.tf
common/state-backend-template
common/variables.tf
instance/.gitignore
instance/config_templates.tfvars
instance/main.tf
instance/state-backend-template
instance/variables.tf

Fixes #6
Creating infrastructure in both `public` and `china` environment works.

feat: allow azure china via 'environment'

---

.gitignore
common/kubeconf.tf
common/outputs.tf

See https://github.com/dspace-group/simphera-reference-architecture-azure/issues/8 and https://github.com/dspace-group/simphera-reference-architecture-azure/issues/4

expose kube_config as output and additionally as local file

---

main.tf
modules/simphera_instance/main.tf

Works fine when tested. Could build and destroy architecture without problems

Updates azurem provider to 2.85

---

.gitignore
README.md
k8s.tf
log-analytics.tf
main.tf
modules/simphera_instance/main.tf
modules/simphera_instance/postgresql.tf
modules/simphera_instance/variables.tf
network.tf
simphera-instances.tf
terraform.tfvars.example
variables.tf

- Update azurerm provider from 2.85.0 to 3.27.0
- Support managed postgresql basic tier with firewall rules
- Set default Kubernetes version to 1.23.12

Postgresql basic tier

---

k8s.tf

Fixes this security rule:
https://portal.azure.com/#blade/Microsoft_Azure_Security/RecommendationsBlade/assessmentKey/0642d770-b189-42ef-a2ce-9dcc3ec6c169

feat: Azure policy enabled

---

README.md
license-server.tf
variables.tf

This fix satisfies the Azure recommendation [*Virtual machines should encrypt temp disks, caches, and data flows between Compute and Storage resources*](https://portal.azure.com/#blade/Microsoft_Azure_Security/RecommendationsBlade/assessmentKey/d57a4221-a804-52ca-3dea-768284f06bb7)

feat: Azure disk encryption of license server

---

README.md
license-server.tf
main.tf
modules/simphera_instance/minio-storage.tf
modules/simphera_instance/postgresql.tf
modules/simphera_instance/secrets.tf
modules/simphera_instance/variables.tf
secrets.tf
simphera-instances.tf
variables.tf

Removes secrets from terraform state.

feat: remove secrets from state

---

README.md
k8s.tf
terraform.tfvars.example
variables.tf

- Restrict API server access to authorized API addresses
- Remove default {} from the variable simpheraInstances

feat: restrict api server access to authorized ip ranges

---

README.md
k8s.tf
variables.tf

The admin can configure the scaleDownMode of the node pools.

Scale down mode

---

README.md
license-server.tf
terraform.tfvars.example
variables.tf

Add option for adding extension for Microsoft guest configuration and option for enabling  SystemAssigned identity for license server.

Add Microsoft guest extension

---

keyvault.tf

Adding of:
- Key vault private endpoint
- Key vault network interface
This change satisfies the Azure recommendation: https://portal.azure.com/#view/Microsoft_Azure_Security/GenericRecommendationDetailsBlade/assessmentKey/2e96bc2f-1972-e471-9e70-ae58d41e9d2a/showSecurityCenterCommandBar~/false

Add keyvault private endpoint

---

README.md
minio-network.tf
modules/simphera_instance/minio-storage.tf
modules/simphera_instance/variables.tf
simphera-instances.tf

Add private endpoint for MinIO storage on azure
This change satisfies the Azure recommendation for MinIO storage: https://portal.azure.com/#view/Microsoft_Azure_Security/GenericRecommendationDetailsBlade/assessmentKey/ad4f3ff1-30eb-5042-16ed-27198f640b8d/showSecurityCenterCommandBar~/false

Add private endpoint for minio storage

---

modules/simphera_instance/minio-storage.tf
network.tf

This PR should fulfill this policy: https://portal.azure.com/#view/Microsoft_Azure_Security/GenericRecommendationDetailsBlade/assessmentKey/ad4f3ff1-30eb-5042-16ed-27198f640b8d/showSecurityCenterCommandBar~/false

Add firewall configuration for minio storage

---

keyvault.tf

Enable purge protection for key vault resource that is required by azure policy:
https://portal.azure.com/#view/Microsoft_Azure_Security/GenericRecommendationDetailsBlade/assessmentKey/4ed62ae4-5072-f9e7-8d94-51c76c48159a/showSecurityCenterCommandBar~/false/assessmentOwners~/null

Enable keyvault purge protection

---

keyvault.tf

Add lifecycle option to key vault resource for access policy.

Add lifecycle to key vault resource

---

keyvault.tf

- Disable purge protection 
- Add private dns zone virtual network link

Update key vault configuration

---

modules/simphera_base/modules/simphera_instance/postgresql.tf
terraform.tfvars.example

- Update version of k8s to 1.24.9
- Remove "=" sign from PostgreSQL password random generator

Update k8s version to 1.24.9

---

main.tf
modules/simphera_base/keyvault.tf
modules/simphera_base/variables.tf
terraform.tfvars.example
variables.tf

- Add key vault purge protection flag via variable

Add key vault purge protection flag

---

README.md
modules/simphera_base/variables.tf
variables.tf

Update of k8s version in variables.tf files and update of terraform doc part of readme file

Fix version of k8s in variables.tf files

---

.github/workflows/qualitygate.yml
.pre-commit-config.yaml
.tflint.hcl
hooks/terraform_format.sh
hooks/terraform_validate.sh
hooks/tflint.sh
hooks/tfsec.sh
hooks/validate_tfvars.sh
main.tf
modules/simphera_base/k8s.tf
modules/simphera_base/keyvault.tf
modules/simphera_base/license-server.tf
modules/simphera_base/modules/simphera_instance/minio-storage.tf
modules/simphera_base/modules/simphera_instance/postgresql.tf
modules/simphera_base/modules/simphera_instance/variables.tf
modules/simphera_base/postgres-network.tf
modules/simphera_base/simphera-instances.tf
modules/simphera_base/variables.tf
terraform.tfvars.example
tfsec.yaml
variables.tf

- Replace Azure Database for PostgreSQL single server by flexible server https://github.com/dspace-group/simphera-reference-architecture-azure/issues/45
- Make Kubernetes Tier configurable https://github.com/dspace-group/simphera-reference-architecture-azure/issues/88
- Replace antonbabenko/pre-commit-terraform with docker_image hooks as it did not work properly on Windows https://github.com/dspace-group/simphera-reference-architecture-azure/issues/60
- Enable geo redundant backups for PostgreSQL https://github.com/dspace-group/simphera-reference-architecture-azure/issues/36
- Enable restore retention of storage accounts https://github.com/dspace-group/simphera-reference-architecture-azure/issues/25
- Enable Azure AD authentication in Azure Database for PostgreSQL by default (required …

Postgresql flexible

---

modules/simphera_base/variables.tf
variables.tf

Sets the default value for the automatic channel upgrade to null to enforce correct mapping

Fixes default value for the k8s upgrade channel

---

terraform.tfvars.example
variables.tf

- use Kubernetes 1.30
- use PostgreSQL 16

update k8s and psql versions
